export enum Role { CLIENT = 'CLIENT', ADMIN = 'ADMIN', CAISSIER = 'CAISSIER' }
export enum StatutCreneau { DISPONIBLE = 'DISPONIBLE', RESERVE = 'RESERVE', BLOQUE = 'BLOQUE' }
export enum StatutReservation { EN_ATTENTE = 'EN_ATTENTE', CONFIRMEE = 'CONFIRMEE', ANNULEE = 'ANNULEE', EXPIREE = 'EXPIREE' }
export enum StatutPaiement { EN_ATTENTE = 'EN_ATTENTE', VALIDE = 'VALIDE', ECHOUE = 'ECHOUE', REMBOURSE = 'REMBOURSE' }
export enum ModePaiement { SUR_PLACE = 'SUR_PLACE', WAVE = 'WAVE', ORANGE_MONEY = 'ORANGE_MONEY', FREE_MONEY = 'FREE_MONEY' }
